"""add perfume table

Revision ID: 462dbc8a7939
Revises: 
Create Date: 2026-09-08 23:27:57.893896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '462dbc8a7939'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfume',
        sa.Column('name', sa.VARCHAR(), nullable=False),
        sa.Column('brand', sa.VARCHAR(), nullable=False),
        sa.Column('type', sa.VARCHAR(), nullable=False),
        sa.Column('gender', sa.VARCHAR(), nullable=False),
        sa.Column('size', sa.INTEGER(), nullable=False),
        sa.Column('stock', sa.INTEGER(), nullable=False),
        sa.Column('price', sa.FLOAT(), nullable=False),
        sa.Column('location', sa.VARCHAR(), nullable=False),
        sa.Column('barcode', sa.VARCHAR(), nullable=False),
        # INTEGER + single-column PRIMARY KEY makes SQLite treat this as an alias
        # for rowid, so an INSERT that omits id gets the next value assigned.
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_perfume_name'), 'perfume', ['name'], unique=False)
    op.create_index(op.f('ix_perfume_id'), 'perfume', ['id'], unique=False)
    # unique=True: one row per SKU. This is what makes POST safe to retry,
    # and it holds for seed data and raw SQL too, not just the endpoint.
    op.create_index(op.f('ix_perfume_barcode'), 'perfume', ['barcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfume_barcode'), table_name='perfume')
    op.drop_index(op.f('ix_perfume_id'), table_name='perfume')
    op.drop_index(op.f('ix_perfume_name'), table_name='perfume')
    op.drop_table('perfume')
    # ### end Alembic commands ###
